### ISSUE TITLE
Missing step in README.md: npm install openzwave-shared

### ISSUE THREAD

**Issue by tommyjlong** [OpenZWave/Zwave2Mqtt#136]
**Version**
2.0.4
Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.4
Openzwave Version: latest (1.6+)

**Describe the bug**
Building from scratch to run on an old 32 bit system plus want to try out openzwave v1.6.
Running `npm start` produces an error about not finding module `openzwave-shared`.

To fix the problem, I also had to run 
`$ npm install openzwave-shared`
This was not mentioned in the README.md
Recommend adding this step in README.md

**To Reproduce**
Followed steps to make and make install openzwave and it installed its various files
in /usr/local/xxxxx (no lib64 here)
Ran `MinOZW /dev/ttyACM0` which ran successfully.

Next (using node v10.16.3 npm v6.9.0):
1. $ npm install
2. $ npm run build
3. $ npm start
4. Get the following error:
```
> zwave2mqtt@2.0.4 start /home/tommy/zwave2mqtt/Zwave2Mqtt
> node bin/www

  z2m:Store settings.json not found +0ms
  z2m:Store scenes.json not found +6ms
  z2m:Store nodes.json not found +1ms
{ Error: Cannot find module '/home/tommy/zwave2mqtt/Zwave2Mqtt/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/tommy/zwave2mqtt/Zwave2Mqtt/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/tommy/zwave2mqtt/Zwave2Mqtt/lib/ZwaveClient.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }

```
**Expected behavior**

**Additional context**
Solution:
1. $ npm install
2. $ npm install openzwave-shared
2. $ npm run build
3. $ npm start

**Comment by robertsLando** [comment]
It is not mentioned because it is part of packege.json so it should be installed when you run npm install with all others dependencies. I think that it has give an error on npm install and this is because you got that problem. Next time keep an eye on the npm install output log and at the end type `npm outdated` to check if there are dependencies not installed
