### ISSUE TITLE
[bug] switching between versions of docker container

### ISSUE THREAD

**Issue by Dinth** [OpenZWave/Zwave2Mqtt#173]
**Version**
Switching between different versions

Build/Run method
- [*] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

**Describe the bug**
Im not sure if this is even a bug, but i thought it maybe something worth noting.
Normally when i delete Z2M docker container and recreate the container using same version of Z2M using following commands:
docker stop container zwave2mqtt
docker rm zwave2mqtt
docker pull ...
docker create ...
docker start container zwave2mqtt
Everything works fine. But, if i also change the version of docker container in the process, for example from :latest to :2.0.6-dev or other way around, the new docker container fails to start with a following error. 
Does it mean that the docker container doesnt release all the hardware resources when being shut down and removed?

```
2019-12-14T19:18:05.038Z z2m:Zwave Connecting to /dev/ttyACM0
TypeError: Cannot read property 'connect' of undefined
    at ZwaveClient.connect (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at Gateway.init (/snapshot/Zwave2Mqtt/lib/Gateway.js:0:0)
    at new Gateway (/snapshot/Zwave2Mqtt/lib/Gateway.js:0:0)
    at startGateway (/snapshot/Zwave2Mqtt/app.js:0:0)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/app.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1259:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1164:31)
    at require (internal/module.js:11:18)
    at require (/snapshot/Zwave2Mqtt/node_modules/app-root-path/lib/app-root-path.js:14:11)
    at jsonStore.init.then.then.then (/snapshot/Zwave2Mqtt/bin/www:0:0)
    at tryCatcher (/snapshot/Zwave2Mqtt/node_modules/bluebird/js/release/util.js:16:23)
(node:1) UnhandledPromiseRejectionWarning: Error: watch /usr/src/app/store/OZW_Log.txt ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at Tail.watch (/snapshot/Zwave2Mqtt/node_modules/tail/lib/tail.js:139:32)
    at new Tail (/snapshot/Zwave2Mqtt/node_modules/tail/lib/tail.js:79:10)
    at ZwaveClient.init (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at new ZwaveClient (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at startGateway (/snapshot/Zwave2Mqtt/app.js:0:0)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/app.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1259:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1164:31)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-12-14T19:18:05.282Z z2m:Mqtt MQTT client connected
```

**Comment by robertsLando** [comment]
@Dinth thanks for the issue, what you mean with:

> Does it mean that the docker container doesnt release all the hardware resources when being shut down and removed?

Actually when the application receives a 'SIGINT' signal it calls gw.close() that should release all resources before closing. This is strange and I think it's something related with docker. 

Could you try to use docker-compose instead? I suggest you to use the commands

```bash
docker-compose up -d # start the container
docker-compose pull # update container with latest docker hub image
docker-compose down # stop 
```

You can find the docker-compose file in Zwave2Mqtt-Docker repo

**Comment by Dinth** [comment]
Hi @robertsLando. At the moment i thing that this bug is incorrect after all. Seems that my Aeotec dongle was somehow "crashing" after few minutes of using with version 1.6 rendering it useless until full system reboot. Im still trying to understand why this was happening and maybe it is a bug, but switching versions is not to blame.
