### ISSUE TITLE
[bug] Precompiled Version 2.2.0 not starting

### ISSUE THREAD

**Issue by raymonvdm** [OpenZWave/Zwave2Mqtt#273]
**2.2.0**

Build/Run method
- [X] PKG

Zwave2Mqtt version: 2.2.0
Openzwave Version: 1.4.3496

**Describe the bug**

The precompiled version off 2.2.0 is not starting on Ubuntu 18.04 since it is compiled using a different version of Node.JS

**To Reproduce**

```

root@mini:/home/homeassistant/Zwave2Mqtt220# unzip zwave2mqtt-v2.2.0.zip 
Archive:  zwave2mqtt-v2.2.0.zip
  inflating: bindings.node           
  inflating: openzwave_shared.node   
   creating: store/
  inflating: zwave2mqtt              
root@mini:/home/homeassistant/Zwave2Mqtt220# ./zwave2mqtt 
  z2m:Store settings.json not found +0ms
  z2m:Store scenes.json not found +3ms
  z2m:Store nodes.json not found +0ms
Error: The module '/home/homeassistant/Zwave2Mqtt220/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:680:18)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)
    at bindings (/snapshot/Zwave2Mqtt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
root@mini:/home/homeassistant/Zwave2Mqtt220# 
```

**Expected behavior**

Normal startup

**Additional context**

**Comment by robertsLando** [comment]
@raymonvdm OZW 1.4 is not supported anymore, check https://github.com/OpenZWave/Zwave2Mqtt#-attention-

**Comment by raymonvdm** [comment]
Check didn`t notice that OZW switched to 1.6, i just installed this machine a week ago with 1.4
