### ISSUE TITLE
v3.0.0 package fails to start with error about NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by seizedengine** [OpenZWave/Zwave2Mqtt#296]
Version
Build/Run method

- [ ] Docker
- [x] PKG 
- [ ] Manually built (git clone - npm install - npm run build )

Zwave2Mqtt version: 3.0.0
Openzwave Version: 1.6
Node version installed is v12.16.1

This is probably on me, or I am missing something. Things worked on v2.1.0. Also, Zwave2MQTT is fantastic, I have been running it for a few months now and it has been dead reliable.

I have tried this a few different ways, but the below is a clean unzip into a new folder. I have already upgraded to OpenZwave 1.6 and it seems to work by itself.
`root@zwave:/home/zwave/zwave2mqtt-test# MinOZW -v
Starting MinOZW with OpenZWave Version 1.6-1045-g8ca59b1d
2020-03-03 17:13:58.266 Error, Cannot find a path to the configuration files at ../../../config/, Using /usr/local/etc/openzwave/ instead...
2020-03-03 17:13:58.267 Info, Reading /usr/local/etc/openzwave/options.xml for Options
2020-03-03 17:13:58.267 Warning, Failed to Parse options.xml: Failed to open file`

However the pkg install fails to run. I had NodeJS v10 installed previously, saw these errors and thought I had to upgrade to v12.16.1 but that didnt work either. So I assume I am missing something. I couldnt find any issues with similar errors though.

`root@zwave:/home/zwave/zwave2mqtt-test# ./zwave2mqtt 
  z2m:Store settings.json not found +0ms
  z2m:Store scenes.json not found +2ms
  z2m:Store nodes.json not found +0ms
Error: The module '/home/zwave/zwave2mqtt-test/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:680:18)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)
    at bindings (/snapshot/Zwave2Mqtt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)`

Thank you!

**Comment by robertsLando** [comment]
@seizedengine Try to use Node `v12.14.1`

**Comment by robertsLando** [comment]
Seems that after upgrading to nodejs 12 some deps were not rebuilded (strange). Will fix this in next release 3.0.1

**Comment by robertsLando** [comment]
@seizedengine Check https://github.com/OpenZWave/Zwave2Mqtt/releases/tag/v3.0.1

**Comment by robertsLando** [comment]
@seizedengine Sorry, the pkg script had a typo, fixed now :) retry to download the pkg zip

**Comment by seizedengine** [comment]
> @seizedengine Sorry, the pkg script had a typo, fixed now :) retry to download the pkg zip

That worked, thank you! I was just coming to report that removing node seemed to fix it too for some reason, but my testing with that would have been with your newest release download so that can be ignored. Thank you for all the fixes!
