### ISSUE TITLE
[bug] npm crashes on node alive with TypeError

### ISSUE THREAD

**Issue by gdave321** [OpenZWave/Zwave2Mqtt#324]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.1
Openzwave Version: 1.6.1031

**Describe the bug**
When a node comes alive npm crashes with TypeError: Cannot set property '128-1-0' of undefined

**To Reproduce**
1. Node not in client setup
2. Add client in application (uses hass output), node is reported as dead to clientapp.
3. Now activate the node by simply walking past it, it's a battery operated motion sensor PST02-A
4. npm reports node comes alive but then immediately crashes.

**Expected behavior**
Simply continuing operation

**Additional context**
2020-03-24 10:37:40.779 Error, Node017, WARNING: node revived
2020-03-24 10:37:40.779 Detail, Node017, AdvanceQueries queryPending=1 queryRetries=0 queryStage=CacheLoad live=1                                                 
2020-03-24 10:37:40.780 Info, Node017, Multi-command frame received, encapsulates 4 command(s)
2020-03-24 10:37:40.780 Info, Node017, Received Battery report from node 17: level=100
2020-03-24 10:37:40.780 Detail, Node017, Initial read of value
2020-03-24 10:37:40.780 Info, Node017, Got a AlarmCmd_Report Message.... 
2020-03-24 10:37:40.780 Info, Node017, Received Notification report (>v1): Type: Home Security (7) Event: Motion Detected at Unknown Location (8) Status: true, Param Length: 0
2020-03-24 10:37:40.780 Detail, Node017, Initial read of value
2020-03-24 10:37:40.780 Info, Node017, Received SensorMultiLevel report from node 17, instance 1, Illuminance: value=11%
2020-03-24 10:37:40.780 Detail, Node017, Initial read of value
2020-03-24 10:37:40.780 Info, Node017, Received SensorMultiLevel report from node 17, instance 1, Air Temperature: value=20.5C
2020-03-24 10:37:40.780 Detail, Node017, Initial read of value
2020-03-24 10:37:40.780 Info, Node017, Multi-command, all 4 command(s) processed
2020-03-24 10:37:40.781 Detail, Node017, Notification: Notification - Node Alive
2020-03-24 10:37:40.781 Detail, Node017, Notification: ValueChanged CC: COMMAND_CLASS_BATTERY Instance: 1 Index: 0                                                
2020-03-24 10:37:40.781 Detail, Node017, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7
2020-03-24 10:37:40.781 Detail, Node017, Notification: ValueChanged CC: COMMAND_CLASS_SENSOR_MULTILEVEL Instance: 1 Index: 3
2020-03-24 10:37:40.781 Detail, Node017, Notification: ValueChanged CC: COMMAND_CLASS_SENSOR_MULTILEVEL Instance: 1 Index: 1
 z2m:Zwave Notification from node 17: Notification - Node Alive (6) +5s
/opt/zwave2mqtt/lib/ZwaveClient.js:463
    ozwnode.values[value_id] = valueId
                             ^

TypeError: Cannot set property '128-1-0' of undefined
    at ZwaveClient.valueChanged (/opt/zwave2mqtt/lib/ZwaveClient.js:463:30)
    at OZW.emit (events.js:203:15)
mnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zwave2mqtt@3.0.1 start: `node bin/www`
npm ERR! Exit status 1

**Comment by robertsLando** [comment]
@gdave321 Thanks, fixed
