### ISSUE TITLE
[bug/question] Segmentation fault

### ISSUE THREAD

**Issue by cyclops1982** [OpenZWave/Zwave2Mqtt#353]
Master Brach

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master branch
Openzwave Version: master branch

**Describe the bug**
Sometimes, i get a segmentation fault. Not during normal operation, but it does happen.

**To Reproduce**
1. Do stuff

```
  z2m:Zwave ValueAdded: 39-115-1-2 Set Powerlevel +1ms
  z2m:Zwave ValueAdded: 39-115-1-3 Test Node +1ms
  z2m:Zwave ValueAdded: 39-115-1-4 Test Powerlevel +1ms
  z2m:Zwave ValueAdded: 39-115-1-5 Frame Count +1ms
  z2m:Zwave ValueAdded: 39-115-1-6 Test +2ms
  z2m:Zwave ValueAdded: 39-115-1-7 Report +2ms
  z2m:Zwave ValueAdded: 39-115-1-8 Test Status +1ms
  z2m:Zwave ValueAdded: 39-115-1-9 Acked Frames +1ms
  z2m:Zwave ValueAdded: 39-128-1-0 Battery Level +1ms
  z2m:Zwave ValueAdded: 39-132-1-1 Minimum Wake-up Interval +1ms
  z2m:Zwave ValueAdded: 39-132-1-2 Maximum Wake-up Interval +2ms
  z2m:Zwave ValueAdded: 39-132-1-3 Default Wake-up Interval +1ms
  z2m:Zwave ValueAdded: 39-132-1-4 Wake-up Interval Step +1ms
  z2m:Zwave ValueAdded: 39-132-1-0 Wake-up Interval +1ms
  z2m:Zwave ValueAdded: 39-134-1-0 Library Version +1ms
  z2m:Zwave ValueAdded: 39-134-1-1 Protocol Version +1ms
  z2m:Zwave ValueAdded: 39-134-1-2 Application Version +2ms
  z2m:Zwave ValueAdded: 39-152-1-0 Secured +1ms
  z2m:App Zwave api call: refreshNodeInfo [ 39 ] +23s
Segmentation fault

npm ERR! Linux 4.15.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! zwave2mqtt@3.0.2 start: `node bin/www`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the zwave2mqtt@3.0.2 start script 'node bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zwave2mqtt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zwave2mqtt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zwave2mqtt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/home/homeass/Zwave2Mqtt/npm-debug.log
```

The npm-debug.log:

```
[22:18:49] root@jubilee:/data/home/homeass/Zwave2Mqtt (master)# cat /data/home/homeass/Zwave2Mqtt/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zwave2mqtt@3.0.2~prestart: zwave2mqtt@3.0.2
6 silly lifecycle zwave2mqtt@3.0.2~prestart: no script for prestart, continuing
7 info lifecycle zwave2mqtt@3.0.2~start: zwave2mqtt@3.0.2
8 verbose lifecycle zwave2mqtt@3.0.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle zwave2mqtt@3.0.2~start: PATH: /usr/share/npm/bin/node-gyp-bin:/data/home/homeass/Zwave2Mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle zwave2mqtt@3.0.2~start: CWD: /data/home/homeass/Zwave2Mqtt
11 silly lifecycle zwave2mqtt@3.0.2~start: Args: [ '-c', 'node bin/www' ]
12 silly lifecycle zwave2mqtt@3.0.2~start: Returned: code: 139  signal: null
13 info lifecycle zwave2mqtt@3.0.2~start: Failed to exec start script
14 verbose stack Error: zwave2mqtt@3.0.2 start: `node bin/www`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid zwave2mqtt@3.0.2
16 verbose cwd /data/home/homeass/Zwave2Mqtt
17 error Linux 4.15.0-33-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error zwave2mqtt@3.0.2 start: `node bin/www`
22 error Exit status 139
23 error Failed at the zwave2mqtt@3.0.2 start script 'node bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the zwave2mqtt package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs zwave2mqtt
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls zwave2mqtt
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Expected behavior**
Not a segmentation fault

**Additional context**
I would really like to know how to troubleshoot this.

**Comment by robertsLando** [comment]
@Fishwaldo Something known?

**Comment by Fishwaldo** [comment]
????
There is nothing in the logs that is specific to OZW...

**Comment by robertsLando** [comment]
Usually segfault happens when something breaks in C layers, maybe it’s something on node-openzwave-shared, I can only see there is an error with an emitter in npm-debug but there is no line or else specified so it’s difficult to know where it comes from. 

Does this happen pnly when sending refreshNodeInfo? 

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by cyclops1982** [comment]
HI guys,
it doesn't always happen. So it's not really reproducible.

This is why i asked how to troubleshoot/debug this. I'm quite new to nodejs, but have expirience debugging/troubleshooting .net and c++ applications. So, if you guys can give me some hints, than that would help me get you more details :)

**Comment by robertsLando** [comment]
@cyclops1982 We could use [segfault-handler](https://github.com/ddopson/node-segfault-handler)

Clone the repository: `git clone https://github.com/OpenZWave/Zwave2Mqtt.git`
Add node js segfault handler to deps: `npm install segfault-handler`

Add this lines at the end of app.js file

```
var SegfaultHandler = require('segfault-handler');
SegfaultHandler.registerHandler(utils.joinPath(true, "segfault.log"));
```

**Comment by pboers1988** [comment]
Hi perhaps I can help, I also have been experiencing seg faults and have an accurate and reliable way to trigger it (if that is a good thing?? ;)) When I update the my fibaro dimmer through an mqtt command, the segfault gets triggered and the app restarts.

**This is the long of MQTT**

As you can see it receives the message and then just dies and respawns.

```bash
2020-04-29T19:04:14.904Z z2m:Mqtt Message received on homeassistant/Woonkamer/Woonkamer-Dimmer/38/1/0/set
[29/Apr/2020:21:04:14 +0200] 200 -(10.0.0.40) GET /socket.io/?EIO=3&transport=polling&t=N77KoIk&sid=hSMatRfN9cd4AdlcAAAD HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15)
2020-04-29 21:04:14.910 Info, Node004, Value::Set - COMMAND_CLASS_SWITCH_MULTILEVEL - Level - 0 - 1 - 51
2020-04-29 21:04:14.911 Info, Node004, SwitchMultilevel::Set - Setting to level 51
2020/04/29 21:04:15 [error] 415#415: *205 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.0.0.40, server: a0d7b954-zwave2mqtt, request: "GET /socket.io/?EIO=3&transport=polling&t=N77KqCp&sid=hSMatRfN9cd4AdlcAAAD HTTP/1.1", upstream: "http://127.0.0.1:44920/socket.io/?EIO=3&transport=polling&t=N77KqCp&sid=hSMatRfN9cd4AdlcAAAD", host: "10.0.0.32:8091", referrer: "http://10.0.0.32:8091/"
[29/Apr/2020:21:04:15 +0200] 502 -(10.0.0.40) GET /socket.io/?EIO=3&transport=polling&t=N77KqCp&sid=hSMatRfN9cd4AdlcAAAD HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15)
2020/04/29 21:04:15 [error] 415#415: *205 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.40, server: a0d7b954-zwave2mqtt, request: "POST /socket.io/?EIO=3&transport=polling&t=N77KqKo&sid=hSMatRfN9cd4AdlcAAAD HTTP/1.1", upstream: "http://127.0.0.1:44920/socket.io/?EIO=3&transport=polling&t=N77KqKo&sid=hSMatRfN9cd4AdlcAAAD", host: "10.0.0.32:8091", referrer: "http://10.0.0.32:8091/"
[29/Apr/2020:21:04:15 +0200] 502 -(10.0.0.40) POST /socket.io/?EIO=3&transport=polling&t=N77KqKo&sid=hSMatRfN9cd4AdlcAAAD HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15)
[21:04:15] INFO: Starting the Z-Wave to MQTT...
2020-04-29T19:04:16.046Z z2m:Store scenes.json not found
2020-04-29T19:04:16.873Z z2m:Gateway No customDevices file found
2020-04-29T19:04:16.878Z z2m:App Application path:/opt
2020/04/29 21:04:16 [error] 415#415: *205 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.40, server: a0d7b954-zwave2mqtt, request: "GET /socket.io/?EIO=3&transport=polling&t=N77KqiE HTTP/1.1", upstream: "http://127.0.0.1:44920/socket.io/?EIO=3&transport=polling&t=N77KqiE", host: "10.0.0.32:8091", referrer: "http://10.0.0.32:8091/"
[29/Apr/2020:21:04:16 +0200] 502 -(10.0.0.40) GET /socket.io/?EIO=3&transport=polling&t=N77KqiE HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15)
Initialising OpenZWave 1.6.974 binary addon for Node.JS.
	OpenZWave Security API is ENABLED
	ZWave device db    : etc/openzwave/
	User settings path : /opt/store
	Option Overrides : --Logging true --ConsoleOutput true --QueueLogLevel 8 --DriverMaxAttempts 9999 --SaveConfiguration true --PollInterval 60000 --AutoUpdateConfigFile true
2020-04-29T19:04:17.061Z z2m:Zwave Connecting to /dev/ttyACM0
```

**This is the corresponding log entry in the dmesg of Ubuntu**

```bash
[wo apr 29 21:03:56 2020] node[5685]: segfault at 63 ip 00007f0bf6da9bc4 sp 00007ffd71293450 error 4 in libopenzwave.so.1.6[7f0bf6d5b000+9c000]
```

I was unsure whether to post it here or [here](https://github.com/OpenZWave/open-zwave)

But decided to do it here first.

If necessary I can do the steps described above. Let me know.

**Comment by robertsLando** [comment]
@Fishwaldo Based on this, it's something on your side

**Comment by robertsLando** [comment]
@pboers1988 Could you tell me also the Z2M version you are using?

**Comment by pboers1988** [comment]
Hi @robertsLando I’m using the most recent packaged version with Home assistant, I believe thats 3.0.2

**Comment by pboers1988** [comment]
Actually Im also able to reproduce the same behavior via the user interface. By updating the dimmer setting to an arbitrary number the system crashes. Sometimes after sending the update on the network, but usually before.

**Comment by robertsLando** [comment]
@pboers1988 Ok it's an OZW problem so, please open the issue there to be sure @Fishwaldo will check it :)

**Comment by pboers1988** [comment]
Cool! Will do thanks.
