### ISSUE TITLE
Support HUSBZB-1

### ISSUE THREAD

**Issue by broyuken** [OpenZWave/Zwave2Mqtt#371]
**Is your feature request related to a problem? Please describe.**
Zigbee2Mqtt won't start with my HUSBZB-1 stick

**Describe the solution you'd like**
ZIgbee2mqtt to work with my HUSBZB-1 stick

**Describe alternatives you've considered**
Use the built in ZHA or Deconz

```
zigbee2mqtt:info  2020-04-22 21:44:51: Starting zigbee2mqtt version 1.12.2 (commit #unknown)
zigbee2mqtt:info  2020-04-22 21:44:51: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-04-22 21:44:58: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-04-22 21:44:58: Failed to start zigbee
zigbee2mqtt:error 2020-04-22 21:44:58: Exiting...
zigbee2mqtt:error 2020-04-22 21:44:58: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code
 ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.12.2 start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.12.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR!
 A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-23T01_44_58_760Z-debug.log
2020-04-22T21:45:00: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-04-22T21:45:00: PM2 log: App [npm:0] starting in -fork mode-
2020-04-22T21:45:00: PM2 log: App [npm:0] online
```

**Comment by robertsLando** [comment]
@broyuken I think you are in the wrong repo :) that's zegbee2mqtt :)

**Comment by broyuken** [comment]
I think you are correct!
