### ISSUE TITLE
Cannot rebuild openzwave-shared@1.5.1

### ISSUE THREAD

**Issue by rgruyters** [OpenZWave/Zwave2Mqtt#46]
I have issues installing the npm packages with OpenZwave2Mqtt version 1.1.3.

```
root@83e2f7f43730:/opt$ npm install openzwave-shared@1.5.1

> openzwave-shared@1.5.1 preinstall /opt/node_modules/openzwave-shared
> node lib/install-ozw.js


> openzwave-shared@1.5.1 install /opt/node_modules/openzwave-shared
> node-gyp rebuild

Illegal option -p
nm: 'a.out': No such file
gyp: Call to 'ldconfig -p | grep 'libopenzwave.so ' | awk '{print $4}' | xargs nm -g --demangle |grep OpenZWave::Value::GetTypeNameFromEnum | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/openzwave-shared
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN zwave2mqtt@1.1.3 No repository field.
npm WARN zwave2mqtt@1.1.3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T09_31_19_381Z-debug.log
```

I have uploaded the logfile to my gist: https://gist.github.com/rgruyters/28825da79ee6ad479f134e9b14f71015

I don't have any issues when I install version 1.4.8 of openzwave-shared.

Is this a known issue?

**Comment by robertsLando** [comment]
Yes, it is, I'm working on it

**Comment by robertsLando** [comment]
It's related to https://github.com/OpenZWave/node-openzwave-shared/issues/320
