### ISSUE TITLE
[bug] SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by TXC** [OpenZWave/Zwave2Mqtt#528]
**Version**
zwave2mqtt@3.2.1 build

Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: v3.2.1
Openzwave Version: 1.6.1133

**Describe the bug**
```
npm run build

> zwave2mqtt@3.2.1 build /home/txc/src/Zwave2Mqtt
> node build/build.js

/home/txc/src/Zwave2Mqtt/node_modules/jest-worker/build/WorkerPool.js:25
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/src/Zwave2Mqtt/node_modules/jest-worker/build/index.js:18:42)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```

**To Reproduce**
1. git clone
2. npm install
3. npm run build

**Expected behavior**
No errors

**Additional context**
-

**Comment by TXC** [comment]
Closing this, 3rd party module issue

**Comment by robertsLando** [comment]
@TXC Could you tell me what was wrong?

**Comment by cinhcet** [comment]
I had the same issue. The solution was to add a bracket `(e)` here node_modules/jest-worker/build/WorkerPool.js:25
