### ISSUE TITLE
[question] npm run build fails on raspberry pi (and release binary is not arm format?)

### ISSUE THREAD

**Issue by sofakng** [OpenZWave/Zwave2Mqtt#562]
I'm trying to run zwave2mqtt on my Raspberry Pi 3.  I have NodeJS v14.4.0 installed and have installed all dependency packages (i.e. "npm install -g").

```
sofakng@rpi-ha:/usr/local/src/zwave2mqtt $ sudo npm run build

> zwave2mqtt@3.2.2 build /usr/local/src/zwave2mqtt
> node build/build.js

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /usr/local/src/zwave2mqtt/build/check-versions.js
- /usr/local/src/zwave2mqtt/build/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/usr/local/src/zwave2mqtt/build/check-versions.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/src/zwave2mqtt/build/check-versions.js',
    '/usr/local/src/zwave2mqtt/build/build.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zwave2mqtt@3.2.2 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zwave2mqtt@3.2.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-08T13_21_04_024Z-debug.log

```

However, chalk is installed:
```
sofakng@rpi-ha:/usr/local/src/zwave2mqtt $ npm ls -g chalk
/usr/lib
├── chalk@4.0.0
└─┬ npm@6.14.5
  └─┬ update-notifier@2.5.0
    ├─┬ boxen@1.3.0
    │ └── chalk@2.4.1  deduped
    └── chalk@2.4.1
```

I also can't run the binary from the release zip:
```
sofakng@rpi-ha:~/zwave2mqtt $ ./zwave2mqtt
-bash: ./zwave2mqtt: cannot execute binary file: Exec format error
```

**Comment by robertsLando** [comment]
@sofakng `npm ls -g chalk` in this way you have checked it is installed globally not locally in the repo

**Comment by sofakng** [comment]
Sorry, I'm not familiar with NodeJS.  I was trying to install the dependencies globally.

For example, I cloned zwave2mqtt into /usr/local/src/zwave2mqtt.  Afterwards I ran "npm install -g" from that directly to install the dependencies.

Do I need to install the dependencies directly into the zwave2mqtt directory?

**Comment by robertsLando** [comment]
> Sorry, I'm not familiar with NodeJS. I was trying to install the dependencies globally.

That is wrong. When you run `npm install` inside the cloned repo folder you will install deps inside that folder (in node_modules folder). Follow steps in readme (nodejs build section)

**Comment by sofakng** [comment]
Got it.  Thanks!  I'm now having problems running npm run build.  (JavaScript heap out of memory)

Do you want me to open a new issue?

```
root@rpi-ha:/usr/local/src/zwave2mqtt# npm run build

> zwave2mqtt@3.2.2 build /usr/local/src/zwave2mqtt
> node build/build.js

⠴ building for production...
<--- Last few GCs --->

[2597:0x3c67650]   179040 ms: Mark-sweep 230.9 (236.1) -> 229.9 (233.4) MB, 663.7 / 0.3 ms  (+ 0.3 ms in 24 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 768 ms) (average mu = 0.197, current mu = 0.136) allocation fail[2597:0x3c67650]   179769 ms: Mark-sweep 230.5 (233.4) -> 230.1 (233.6) MB, 709.1 / 0.2 ms  (average mu = 0.121, current mu = 0.027) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! zwave2mqtt@3.2.2 build: `node build/build.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the zwave2mqtt@3.2.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-08T13_47_14_124Z-debug.log
```

**Comment by robertsLando** [comment]
hemmm try to give nodejs more memory when running the command

`node  --max-old-space-size=4096 build/build.j`

**Comment by sofakng** [comment]
That fixed it . Thanks!
