### ISSUE TITLE
Error on start-up

### ISSUE THREAD

**Issue by dooz127** [OpenZWave/Zwave2Mqtt#683]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.1
Openzwave Version: 1.6.1240

**Describe the bug**
I get the following output when I start up zwave2mqtt:

```
Initialising OpenZWave 1.6.1240 binary addon for Node.JS.

	OpenZWave Security API is ENABLED

	ZWave device db    : /usr/src/open-zwave/config

	User settings path : /usr/src/app/store

	Option Overrides : --Logging undefined --ConsoleOutput undefined --QueueLogLevel 6 --DriverMaxAttempts 9999 --SaveConfiguration false --PollInterval 1000 --AutoUpdateConfigFile false --NetworkKey REDACTED

  z2m:Zwave Connecting to /dev/zwave +0ms

2020-08-22 15:29:23.689 Always, OpenZwave Version 1.6-1240-g01c8d001 Starting Up

2020-08-22 15:29:23.697 Always, Using Language Localization 

  z2m:Zwave Zwave connected, Openzwave version: 1.6.1240 +477ms

  z2m:App Listening on port 8091 +0ms

/usr/src/app/lib/Gateway.js:51

        fn()

        ^
TypeError: fn is not a function

    at FSWatcher.<anonymous> (/usr/src/app/lib/Gateway.js:51:9)

    at FSWatcher.emit (events.js:315:20)

    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:135:12)
```

**To Reproduce**
1. Start up zwave2mqtt docker container

**Comment by robertsLando** [comment]
Sorry guys I release 4.0.2 now
