### ISSUE TITLE
[bug] missing scenes.json

### ISSUE THREAD

**Issue by ZimoSka** [OpenZWave/Zwave2Mqtt#711]
4.0.3

Build/Run method
- [ ] Docker
- [ ] PKG
- [*] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.3
Openzwave Version: 1.6-1279

**Describe the bug**
after several hours of running z2m is failing to start due to missing scenes.json

  z2m:Store scenes.json not found +0ms
Error: libopenzwave.so.1.6: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1023:18)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:6:15)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)

checked store/scenes.json - it's missing.

To workaround, please provide structure of empty scenes.json.

**Comment by ZimoSka** [comment]
seems that it was issue of some dead device on controller, after controller factory reset everything seems to be ok.
