### ISSUE TITLE
zwave2mqtt not starting on reboot

### ISSUE THREAD

**Issue by Altycoder** [OpenZWave/Zwave2Mqtt#843]
Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.1.0
Openzwave Version: 1.6.0

After updating to the latest image 2 days ago, when I restart my Arch (LTS kernel) server, zwave2mqtt does not start correctly (doesn't function, nothing operating on port 8091) - nothing is feeding through to mosquitto.  I need to recreate the container to get it going.  Restarting the container does not fix the issue.

All my other containers are functioning normally.  This has only started happening since the latest image update.

Log from portainer:

```
Initialising OpenZWave 1.6.0 binary addon for Node.JS.

	OpenZWave Security API is ENABLED

	ZWave device db    : /usr/local/etc/openzwave

	User settings path : /usr/src/app/store

	Option Overrides : --Logging true --ConsoleOutput true --QueueLogLevel 8 --DriverMaxAttempts 9999 --SaveConfiguration true --PollInterval 60000 --AutoUpdateConfigFile true --NetworkKey 0xFE,0x03,0xDC,0xAB,0x01,0x06,0x07,0xAA,0x06,0x0A,0x0E,0x0C,0x45,0x47,0xDD,0xBB --AssumeAwake true

  z2m:Zwave Connecting to /dev/ttyACM0 +0ms

2020-12-02 09:39:53.294 Always, OpenZwave Version 1.6.-1 Starting Up

2020-12-02 09:39:53.314 Info, Loading Localization File /usr/local/etc/openzwave/Localization.xml

2020-12-02 09:39:53.317 Info, Loaded /usr/local/etc/openzwave/Localization.xml With Revision 12

2020-12-02 09:39:53.319 Always, Using Language Localization 

2020-12-02 09:39:53.321 Info, Loading NotificationCCTypes File /usr/local/etc/openzwave/NotificationCCTypes.xml

2020-12-02 09:39:53.321 Info, Loaded /usr/local/etc/openzwave/NotificationCCTypes.xml With Revision 11

2020-12-02 09:39:53.323 Info, Loading SensorMultiLevelCCTypes File /usr/local/etc/openzwave/SensorMultiLevelCCTypes.xml

2020-12-02 09:39:53.323 Info, Loaded /usr/local/etc/openzwave/SensorMultiLevelCCTypes.xml With Revision 4

2020-12-02 09:39:53.324 Info, Setting Up Provided Network Key for Secure Communications

2020-12-02 09:39:53.324 Info, Unable to load /usr/local/etc/openzwave/manufacturer_specific.xml

2020-12-02 09:39:53.324 Warning, Exception: ManufacturerSpecificDB.cpp:74 - 1 - Cannot Load/Read ManufacturerSpecificDB! - Missing/Invalid Config File?

Error: Exception calling OpenZWave::Manager::AddDriver in /openzwave/cpp/src/ManufacturerSpecificDB.cpp(74): Cannot Load/Read ManufacturerSpecificDB! - Missing/Invalid Config File?

    at ZwaveClient.connect (/usr/src/app/lib/ZwaveClient.js:985:17)

    at Gateway.init (/usr/src/app/lib/Gateway.js:160:11)

    at new Gateway (/usr/src/app/lib/Gateway.js:118:8)

    at startGateway (/usr/src/app/app.js:60:8)

    at Object.<anonymous> (/usr/src/app/app.js:258:1)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at require (/usr/src/app/node_modules/app-root-path/lib/app-root-path.js:14:11)

    at /usr/src/app/bin/www:33:15

    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)

    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)

    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)

  z2m:Mqtt read ECONNRESET +0ms

  z2m:Mqtt MQTT client offline +1ms

  z2m:Mqtt MQTT client closed +0ms

  z2m:Mqtt MQTT client reconnecting +1m

  z2m:Mqtt MQTT client connected +11ms

  z2m:Mqtt Message received on homeassistant/status +3m

  z2m:Gateway Home Assistant is ONLINE +0ms

  z2m:Store scenes.json not found +0ms

  z2m:App Zwave2Mqtt version: 4.1.0 +0ms

  z2m:App Application path:/usr/src/app +0ms

Initialising OpenZWave 1.6.0 binary addon for Node.JS.

	OpenZWave Security API is ENABLED

	ZWave device db    : /usr/local/etc/openzwave

	User settings path : /usr/src/app/store

	Option Overrides : --Logging true --ConsoleOutput true --QueueLogLevel 8 --DriverMaxAttempts 9999 --SaveConfiguration true --PollInterval 60000 --AutoUpdateConfigFile true --NetworkKey 0xFE,0x03,0xDC,0xAB,0x01,0x06,0x07,0xAA,0x06,0x0A,0x0E,0x0C,0x45,0x47,0xDD,0xBB --AssumeAwake true

  z2m:Zwave Connecting to /dev/ttyACM0 +0ms

2020-12-02 10:19:44.915 Always, OpenZwave Version 1.6.-1 Starting Up

2020-12-02 10:19:44.920 Info, Loading Localization File /usr/local/etc/openzwave/Localization.xml

2020-12-02 10:19:44.921 Info, Loaded /usr/local/etc/openzwave/Localization.xml With Revision 12

2020-12-02 10:19:44.922 Always, Using Language Localization 

2020-12-02 10:19:44.923 Info, Loading NotificationCCTypes File /usr/local/etc/openzwave/NotificationCCTypes.xml

2020-12-02 10:19:44.924 Info, Loaded /usr/local/etc/openzwave/NotificationCCTypes.xml With Revision 11

2020-12-02 10:19:44.925 Info, Loading SensorMultiLevelCCTypes File /usr/local/etc/openzwave/SensorMultiLevelCCTypes.xml

2020-12-02 10:19:44.925 Info, Loaded /usr/local/etc/openzwave/SensorMultiLevelCCTypes.xml With Revision 4

2020-12-02 10:19:44.925 Info, Setting Up Provided Network Key for Secure Communications

2020-12-02 10:19:44.925 Info, Unable to load /usr/local/etc/openzwave/manufacturer_specific.xml

2020-12-02 10:19:44.925 Warning, Exception: ManufacturerSpecificDB.cpp:74 - 1 - Cannot Load/Read ManufacturerSpecificDB! - Missing/Invalid Config File?

Error: Exception calling OpenZWave::Manager::AddDriver in /openzwave/cpp/src/ManufacturerSpecificDB.cpp(74): Cannot Load/Read ManufacturerSpecificDB! - Missing/Invalid Config File?

    at ZwaveClient.connect (/usr/src/app/lib/ZwaveClient.js:985:17)

    at Gateway.init (/usr/src/app/lib/Gateway.js:160:11)

    at new Gateway (/usr/src/app/lib/Gateway.js:118:8)

    at startGateway (/usr/src/app/app.js:60:8)

    at Object.<anonymous> (/usr/src/app/app.js:258:1)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at require (/usr/src/app/node_modules/app-root-path/lib/app-root-path.js:14:11)

    at /usr/src/app/bin/www:33:15

    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)

    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)

    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)

  z2m:Mqtt MQTT client connected +0ms
```

**Comment by robertsLando** [comment]
@Altycoder Consider switching to zwavejs2mqtt, The bug seems related to OZW.

https://github.com/zwave-js/zwavejs2mqtt

**Comment by robertsLando** [comment]
@chrisns Maybe we should downgrade to ozw 1.6.1542 (actually it's latest 1.6.2545) http://old.openzwave.com/downloads/

**Comment by Altycoder** [comment]
> @Altycoder Consider switching to zwavejs2mqtt, The bug seems related to OZW.
> 
> https://github.com/zwave-js/zwavejs2mqtt

Why would zwavejs2mqtt be any different / better?  I don't really want to switch if I don't have to....

I thought this may have been a bug with docker or docker-compose as they were updated a few days ago as well, but both have just been updated again via the Arch repo and all my other containers seem fine so I don't think it's that.

**Comment by Altycoder** [comment]
Are you going to stop maintaining zwave2mqtt in favour of zwavejs2mqtt?

**Comment by Altycoder** [comment]
I've just tried pulling zwavejs2mqtt but got an error so wondering what to do now............

**Comment by robertsLando** [comment]
@Altycoder The onyl tag available for zwavejs2mqtt is `dev` until there is a stable release. Anyway I don't plan to stop maintaining zwave2mqtt, this could be solved by down grading ozw version

**Comment by Altycoder** [comment]
> @Altycoder The onyl tag available for zwavejs2mqtt is `dev` until there is a stable release. Anyway I don't plan to stop maintaining zwave2mqtt for now, this could be solved by down grading ozw version. If you check the reason behind that new project you will understand why I suggest you to switch to that
> 
> About the switch it has many breaking changes so please read the readme: https://github.com/zwave-js/zwavejs2mqtt#why-zwavejs

ok but the readme for zwavejs2mqtt says to pull `latest` ;-)

For now I'm going to stick with zwave2mqtt as I don't want to jump just yet.  I'm also going to review the home assistant position on their OZW move as I've lost track of that.

**Comment by robertsLando** [comment]
You right, sorry! Anyway no problem, does if you downgrade to the previous z2m version it works?

**Comment by Altycoder** [comment]
that's my job for this afternoon.  

Do you recommend I go back to:

sha-9311ff98aa6086c85be55c79d6c3b8f2dd6b5435

or

sha-e9553ebcea38a823edfa1edcf19d0f847355c0f8

**Comment by Altycoder** [comment]
or 4.0.6 even?

**Comment by robertsLando** [comment]
4.0.6. If that works Iwill submit a patch release 4.1.1 with a downgraded ozw version

**Comment by Altycoder** [comment]
ok I will give it a try this afternoon and report back

**Comment by Altycoder** [comment]
rolling back to 4.0.6 works

**Comment by robertsLando** [comment]
Ok will downgrade ozw version and release a patch for this. thanks

**Comment by robertsLando** [comment]
@Altycoder 4.1.1 version just released with the fix

**Comment by Altycoder** [comment]
OK thanks I will try this tomorrow if I can

**Comment by robertsLando** [comment]
LMK

**Comment by Altycoder** [comment]
4.1.1. works, thanks

**Comment by robertsLando** [comment]
@Altycoder You welcome :) thanks for the report!
