### ISSUE TITLE
[bug] crash on replace failed node

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#87]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master @ 20190805
Openzwave Version: 1.6.848

**Describe the bug**
When trying to replace a failed node, z2m crashes once we success in repalcing the node. 

**To Reproduce**
1. mark a node as faulty
2. execute a replace failed node
3. enter node node in include mode
4. wait for it to succeed.
5. crash 

**Expected behavior**
No crash

**Additional context**
```
2019-08-08T14:37:58.390Z z2m:App Zwave api call: replaceFailedNode [ 3 ]
2019-08-08T14:37:58.397Z z2m:Zwave Success zwave api call replaceFailedNode true
2019-08-08T14:37:58.398Z z2m:Zwave controller command { nodeid: 3,
  state: 1,
  errcode: 0,
  help: 'AssignReturnRoute Starting' }
2019-08-08T14:37:58.400Z z2m:Zwave controller command { nodeid: 3, state: 3, errcode: 10, help: 'Error - Failed' }
2019-08-08T14:37:58.400Z z2m:Zwave controller command { nodeid: 3,
  state: 1,
  errcode: 0,
  help: 'HasNodeFailed Starting' }
2019-08-08T14:37:58.411Z z2m:Zwave Notification from node 3: Notification - Node Dead (5)
2019-08-08T14:37:58.411Z z2m:Zwave controller command { nodeid: 3,
  state: 10,
  errcode: 0,
  help: 'HasNodeFailed NodeFailed' }
2019-08-08T14:37:58.411Z z2m:Zwave Node removed 3
2019-08-08T14:37:58.412Z z2m:Zwave controller command { nodeid: 3,
  state: 1,
  errcode: 0,
  help: 'ReplaceFailedNode Starting' }
2019-08-08T14:37:58.423Z z2m:Zwave controller command { nodeid: 3,
  state: 6,
  errcode: 0,
  help: 'ReplaceFailedNode InProgress' }
2019-08-08T14:37:58.486Z z2m:Zwave controller command { nodeid: 3,
  state: 9,
  errcode: 0,
  help: 'ReplaceFailedNode NodeOK' }
2019-08-08T14:38:16.201Z z2m:Zwave Notification from node 3: Notification - Node Alive (6)
2019-08-08T14:38:26.202Z z2m:Zwave Notification from node 3: Notification - TimeOut (1)
2019-08-08T14:38:36.208Z z2m:Zwave Notification from node 3: Notification - TimeOut (1)
2019-08-08T14:38:46.209Z z2m:Zwave Notification from node 3: Notification - TimeOut (1)
/opt/zwave2mqtt_16/lib/ZwaveClient.js:345
      oldst = ozwnode.values[value_id].value
                            ^

TypeError: Cannot read property '117-1-0' of undefined
    at ZwaveClient.valueChanged (/opt/zwave2mqtt_16/lib/ZwaveClient.js:345:29)
    at emitThree (events.js:136:13)
    at OZW.emit (events.js:217:7)
[ Aug  8 14:38:46 Stopping because service exited with an error. ]
```

**Comment by robertsLando** [comment]
This is really strange as to get there the node must be ready and if the node is ready it also should have the values object inited... Does this happens every time you replace a failed node?

**Comment by robertsLando** [comment]
Ok got it. Seems that the Node Alive notification sets the node ready to true, but the strange thing is that before that call it should first call node added and node ready event...

**Comment by robertsLando** [comment]
@sjorge  Try now

**Comment by sjorge** [comment]
The crash is gone now, I did have a quick look at the diff...

Do the proper things still happen for dead nodes now?
I would expect `ozwnode.available` to be false if the node is dead (case 5), but I don't know the ozw internals well.

**Comment by robertsLando** [comment]
`ozwnode.available` for me means that the node has been inited (node added, values added and node info received). If the node is dead means that at least I have received it's info from controller but the node isn't alive but I have all it's values even if dead.

**Comment by sjorge** [comment]
👍
